inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 25
  Exclude:
    - 'config/routes.rb'
    - 'spec/**/*'
